import { NextRequest, NextResponse } from "next/server";
import { generateStory } from "@/lib/deepseek";

export const maxDuration = 60;

/**
 * POST /api/generate-story
 * Generates narrative content (explanation, userBridge, story) for a name
 * that was already generated by /api/generate-name.
 *
 * Body: { nameData: NameEntry, englishName?, selfWord?, surname?, sourceCategory, birthYear?, ... }
 */
export async function POST(request: NextRequest) {
  try {
    const body = await request.json();
    const { nameData, ...req } = body;

    if (!nameData || !nameData.chars) {
      return NextResponse.json(
        { error: "nameData with at least chars field is required" },
        { status: 400 }
      );
    }

    const story = await generateStory(nameData, req);

    return NextResponse.json(story);
  } catch (error) {
    console.error("generate-story error:", error);
    return NextResponse.json(
      {
        explanation:
          "A name rooted in centuries of Chinese literary tradition.",
        userBridge:
          "This name carries the weight of Chinese cultural history.",
        storyTitle: "An Ancient Legacy",
        storyBody:
          "Chinese names are not just labels — they are capsules of history, poetry, and philosophy. This name draws from sources that have shaped Chinese civilization for thousands of years.",
      },
      { status: 200 }
    );
  }
}
