import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Disclaimer",
  description:
    "Important disclaimers about Shan Shui — AI-generated content, Bazi analysis limitations, cultural accuracy, and medical/legal advice.",
};

export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-[#F8FAFB]">
      <div className="max-w-2xl mx-auto px-4 py-12">
        <h1 className="text-2xl font-light text-text-primary mb-2">
          Disclaimer
        </h1>
        <p className="text-sm text-text-secondary mb-8">
          Please read these disclaimers carefully before using Shan Shui.
        </p>

        <div className="space-y-6 text-sm text-text-secondary leading-relaxed">
          {/* 1. General */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              1. General Disclaimer
            </h2>
            <p>
              Shan Shui provides AI-generated Chinese name suggestions for
              entertainment, educational, and cultural exploration purposes. The
              names, explanations, stories, and analyses generated by this
              service are created by artificial intelligence and should not be
              considered definitive, authoritative, or professionally verified
              cultural advice.
            </p>
          </section>

          {/* 2. Bazi / Five Elements */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              2. Bazi (八字) & Five Elements Analysis
            </h2>
            <p>
              The Bazi (Four Pillars of Destiny) and Five Elements analysis
              features are provided <strong>for entertainment and cultural
              education only</strong>. They are not:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>A substitute for professional fortune-telling, divination, or metaphysical consultation</li>
              <li>Scientifically validated personality or destiny assessments</li>
              <li>A replacement for psychological counseling, career advice, or life coaching</li>
              <li>Medical, legal, or financial advice of any kind</li>
            </ul>
            <p className="mt-3">
              Bazi is a traditional Chinese cultural practice dating back over
              3,000 years. While we implement established calculation methods,
              interpretations of Bazi charts vary among different schools of
              thought. The AI-generated analysis represents one possible
              interpretation and should not be taken as absolute truth.
            </p>
          </section>

          {/* 3. AI Limitations */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              3. AI-Generated Content
            </h2>
            <p>
              All names, cultural explanations, stories, and analyses are
              generated by artificial intelligence (DeepSeek API). While we
              employ quality validation and fallback mechanisms:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>
                AI may occasionally produce names or explanations that contain
                inaccuracies, anachronisms, or culturally inappropriate content
              </li>
              <li>
                Classical source citations are AI-generated and may contain errors
              </li>
              <li>
                Pronunciation guides are approximations and may not capture
                regional variations
              </li>
              <li>
                We do not guarantee that a generated name will be culturally
                appropriate in all contexts
              </li>
            </ul>
          </section>

          {/* 4. Cultural Sensitivity */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              4. Cultural Sensitivity & Appropriation
            </h2>
            <p>
              Chinese naming is a profound cultural tradition with over 3,000
              years of history. We encourage users to:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>
                Use generated names respectfully, understanding their cultural
                origins
              </li>
              <li>
                Consult with Chinese speakers or cultural experts before using a
                name in formal or professional contexts
              </li>
              <li>
                Recognize that adopting a Chinese name carries cultural weight and
                should not be done frivolously
              </li>
            </ul>
            <p className="mt-3">
              Shan Shui is designed to be a bridge between cultures — not a tool
              for superficial cultural tourism. We encourage all users to engage
              deeply with the stories and philosophies behind their generated
              names.
            </p>
          </section>

          {/* 5. No Professional Advice */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              5. No Professional Advice
            </h2>
            <p>
              Nothing on this website constitutes professional advice of any
              kind — medical, legal, financial, psychological, or otherwise.
              Always consult qualified professionals for decisions affecting your
              health, finances, legal standing, or well-being.
            </p>
          </section>

          {/* 6. Third-Party Services */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              6. Third-Party Services
            </h2>
            <p>
              Shan Shui relies on third-party services including DeepSeek AI
              (name generation), Vercel (hosting), and Google Analytics
              (optional). We are not responsible for the content, accuracy, or
              availability of these third-party services.
            </p>
          </section>

          {/* 7. Limitation of Liability */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              7. Limitation of Liability
            </h2>
            <p>
              TO THE MAXIMUM EXTENT PERMITTED BY LAW, SHAN SHUI AND ITS
              OPERATORS SHALL NOT BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
              SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE
              OF THIS SERVICE, INCLUDING BUT NOT LIMITED TO:
            </p>
            <ul className="list-disc pl-5 space-y-1 mt-2">
              <li>Emotional distress from AI-generated analyses</li>
              <li>Cultural misunderstandings or social consequences</li>
              <li>Decisions made based on Bazi or Five Elements interpretations</li>
              <li>Service interruptions or data loss</li>
              <li>Inaccurate or inappropriate name suggestions</li>
            </ul>
          </section>

          {/* 8. Updates */}
          <section>
            <h2 className="text-base font-medium text-text-primary mb-2">
              8. Changes to This Disclaimer
            </h2>
            <p>
              We may update this disclaimer at any time. Continued use of the
              service after changes constitutes acceptance of the updated terms.
              Last updated: June 2026.
            </p>
          </section>
        </div>

        <div className="mt-10 p-5 rounded-card bg-[#EEF4F8] border border-deep-blue/10">
          <p className="text-xs text-text-secondary leading-relaxed text-center">
            By using Shan Shui, you acknowledge that you have read, understood,
            and agree to this disclaimer. If you do not agree, please do not use
            this service.
          </p>
        </div>
      </div>
    </main>
  );
}
